### PR TITLE
dbname with reserved chars

### PR DESCRIPTION
**Pull request by jhere1**
account for db names with reserved chars, such as "-"

### CODE REVIEW

**Comment by AnatolyUss** [comment]
Hello Jian,
Just wondering, does MySQL (or MariaDB) allow to have DB name, consisting
of several words (or reserved word[s])?
Could you provide an example please?

**Comment by AnatolyUss** [comment]
Ah, ok, I see ))

**Comment by jhere1** [comment]
an example we had would be a db name such as "test-database"  the "-" is a reserved char.

**Review by AnatolyUss — APPROVED** [review]
@jhere1 
Thanks a lot for your attention!
Approved and merged.

**Comment by AnatolyUss** [comment]
@jhere1 
Sorry, I had to revert this change.
It breaks on MySQL 8.0.33 ...
Could you share which MySQL version did you use?

**Pull request merged**
